### ISSUE TITLE
"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."

### ISSUE THREAD

**Issue by Kulikovpavel** [tpyo/amazon-s3-php-class#120] opened 2015-11-29 12:00 UTC
AWS::S3::Errors::InvalidRequest The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

I have same problem, with Frankfurt server, as in this question.
http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

Can you add new type of authorization?

**Comment by p4trizio** [comment] 2015-12-15 15:53
same problem here

**Comment by p4trizio** [comment] 2015-12-15 16:15
Sorry this looks a duplicate of #96

**Comment by amrutanikam** [comment] 2018-08-03 09:54
In case some needs have a look [https://gist.github.com/andybroomfield/2383c19171f0739b77e4b831e1e9ee61]

**Comment by tpyo** [comment] 2019-05-05 19:16
Closed in #128.

**Closed by tpyo** 2019-05-05 19:16 UTC

**Comment by prabhakaran-s-kt** [comment] 2024-01-22 07:57
It seems that this was not included in the most recent version, v0.5.1. Would you kindly update the version that was released?
